name: Pipeline DevSecOps Backend

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  sast-semgrep:
    name: 1. SAST (Semgrep)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Escaneo de codigo Java
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/java

  sca-trivy:
    name: 2. SCA (Trivy Filesystem)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Escaneo de dependencias pom.xml
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

  container-trivy:
    name: 3. Container Security (Trivy)
    runs-on: ubuntu-latest
    needs: [sast-semgrep, sca-trivy]
    steps:
      - uses: actions/checkout@v5
      - name: Construir Imagen Docker
        run: docker build -t backend-spring:${{ github.sha }} .
      - name: Escanear Imagen con Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'backend-spring:${{ github.sha }}'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'